# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.




"""Speect Plug-in for SLexicon class"""


from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_lexicon', [dirname(__file__)])
        except ImportError:
            import _lexicon
            return _lexicon
        if fp is not None:
            try:
                _mod = imp.load_module('_lexicon', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _lexicon = swig_import_helper()
    del swig_import_helper
else:
    import _lexicon
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



__version__ = "1.0.0"
__license__= "mit"

import speect
class SLexicon(_object):
    """

    A lexicon class, for accessing a defined lexicon.

    """

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SLexicon, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SLexicon, name)
    __repr__ = _swig_repr
    __swig_setmethods__["features"] = _lexicon.SLexicon_features_set
    __swig_getmethods__["features"] = _lexicon.SLexicon_features_get
    if _newclass:
        features = _swig_property(_lexicon.SLexicon_features_get, _lexicon.SLexicon_features_set)

    def name(self):
        """

        name()

        Get the name of the lexicon.

        :return: The lexicon name.
        :rtype: string

        """
        return _lexicon.SLexicon_name(self)


    def description(self):
        """

        description()

        Get a description of the lexicon.

        :return: The lexicon description.
        :rtype: string

        """
        return _lexicon.SLexicon_description(self)


    def language(self):
        """

        language()

        Get the lexicon language.

        :return: The lexicon language.
        :rtype: string

        """
        return _lexicon.SLexicon_language(self)


    def lang_code(self):
        """

        lang_code()

        Get the lexicon's ``ISO 639-2`` language code.

        :return: The ``ISO 639-2`` language code of the lexicon.
        :rtype: string

        """
        return _lexicon.SLexicon_lang_code(self)


    def version(self):
        """

        version()

        Get the lexicon's version.

        :return: The version of the lexicon (major, minor).
        :rtype: tuple

        """
        return _lexicon.SLexicon_version(self)


    def get_word(self, word, features=None):
        """
        get_word(word, features)

        Get a word from the lexicon.

        :param word: The word to get.
        :type word: string
        :param features: Specific features which might distinguish the word if multiple
                         entries of the word exists in the lexicon. If ``None`` then the
                         first entry of the word is returned.
        :type features: dict
        :return: The return value is dependent on the word definition in the lexicon, and can be:

                     * A list of phones for the given word (no syllables were defined in the lexicon).
                     * A list of syllables, where the syllables are lists of phones.
                     * ``None`` if word was not found in the lexicon.

                 As well as a ``bool`` value, specifying if the returned list is phones or syllables.
                 If ``True`` then syllables were returned, else if ``False`` a list of phones were
                 returned.

                 For example::

                     list, syllabified = mylexicon.get_word(\"hello\", None)

        :rtype: list, bool
        """

        if not isinstance(word, unicode) and not isinstance(word, str):
            raise TypeError("Argument \"word\" must be a str or unicode type")

        if features is not None and not isinstance(features, dict):
            raise TypeError("Argument \"features\" must be a dict type")

        tmp_tuple = _lexicon_get_word(self, word, features)
        if tmp_tuple is not None:
            wlist = tmp_tuple[0]
            syllabified = tmp_tuple[1]
        else:
            wlist = None
            syllabified = False

        return wlist, syllabified


    def __init__(self):
        """

        A lexicon class, for accessing a defined lexicon.

        """
        this = _lexicon.new_SLexicon()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _lexicon.delete_SLexicon
    __del__ = lambda self: None
SLexicon_swigregister = _lexicon.SLexicon_swigregister
SLexicon_swigregister(SLexicon)


def _lexicon_get_word(arg1, word, features):
    """_lexicon_get_word(SLexicon arg1, char const * word, PyObject * features) -> PyObject *"""
    return _lexicon._lexicon_get_word(arg1, word, features)
# This file is compatible with both classic and new-style classes.


