# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.




"""Speect Plug-in for SMatrixFloat class"""


from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_matrix_float', [dirname(__file__)])
        except ImportError:
            import _matrix_float
            return _matrix_float
        if fp is not None:
            try:
                _mod = imp.load_module('_matrix_float', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _matrix_float = swig_import_helper()
    del swig_import_helper
else:
    import _matrix_float
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



__version__ = "1.0.0"
__license__= "mit"

import speect
class SMatrixFloat(_object):
    """

    SMatrixFloat(mlist)

    A native Speect class for containing an matrix of floating point values.
    Create a new object, that contains an matrix of floating point point values.

    :param mlist: A Python list of lists containing only floating point values.
    :type mlist: list
    :return: Newly created SMatrixFloat object.
    :rtype: SMatrixFloat

    """

    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SMatrixFloat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SMatrixFloat, name)
    __repr__ = _swig_repr
    __swig_getmethods__["row_count"] = _matrix_float.SMatrixFloat_row_count_get
    if _newclass:
        row_count = _swig_property(_matrix_float.SMatrixFloat_row_count_get)
    __swig_getmethods__["col_count"] = _matrix_float.SMatrixFloat_col_count_get
    if _newclass:
        col_count = _swig_property(_matrix_float.SMatrixFloat_col_count_get)

    def __init__(self, fm):
        """

        SMatrixFloat(mlist)

        A native Speect class for containing an matrix of floating point values.
        Create a new object, that contains an matrix of floating point point values.

        :param mlist: A Python list of lists containing only floating point values.
        :type mlist: list
        :return: Newly created SMatrixFloat object.
        :rtype: SMatrixFloat

        """
        this = _matrix_float.new_SMatrixFloat(fm)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _matrix_float.delete_SMatrixFloat
    __del__ = lambda self: None

    def get(self):
        """

        get()

        Return a copy of this SMatrixFloat object as a Python list of lists of floating point
        values.

        :return: Python list of lists floating point values.
        :rtype: list

        """
        return _matrix_float.SMatrixFloat_get(self)

SMatrixFloat_swigregister = _matrix_float.SMatrixFloat_swigregister
SMatrixFloat_swigregister(SMatrixFloat)

# This file is compatible with both classic and new-style classes.


