######################################################################################
##                                                                                  ##
## CMake configuration for named plug-in.                                           ##
## This file is auto generated from plugins/config/pluginConf.cmake.in              ##
##                                                                                  ##
## Do not edit this file.                                                           ##
##                                                                                  ##
######################################################################################


# array_int_ebml include directories
set(array_int_ebml_include_path "/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/serialization/objects/arrays/integer/ebml/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/serialization/objects/arrays/integer/ebml/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/serialization/formats/ebml/src;/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/serialization/formats/ebml/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/utils/arrays/integer/src;/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/utils/arrays/integer/src")


# When included in other plug-in CMakeLists.txt, the above
# header directories will be appended to the plug-ins dirs.
list(APPEND ${plugin_lowercase_name}_INCLUDE_DIRS
  ${array_int_ebml_include_path}
  )


# array_int_ebml version
set(array_int_ebml_VERSION_MAJOR 1)
set(array_int_ebml_VERSION_MINOR 0)
