######################################################################################
##                                                                                  ##
## CMake configuration for named plug-in.                                           ##
## This file is auto generated from plugins/config/pluginConf.cmake.in              ##
##                                                                                  ##
## Do not edit this file.                                                           ##
##                                                                                  ##
######################################################################################


# relp_synthesis include directories
set(relp_synthesis_include_path "/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/acoustic/wave_generation/relp/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/acoustic/wave_generation/relp/src;/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/utils/matrices/float/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/utils/matrices/float/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/utils/tracks/float/src;/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/utils/tracks/float/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/utils/arrays/integer/src;/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/utils/arrays/integer/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/acoustic/audio/src;/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/acoustic/audio/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/acoustic/window_functions/interface/src;/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/acoustic/window_functions/interface/src")


# When included in other plug-in CMakeLists.txt, the above
# header directories will be appended to the plug-ins dirs.
list(APPEND ${plugin_lowercase_name}_INCLUDE_DIRS
  ${relp_synthesis_include_path}
  )


# relp_synthesis version
set(relp_synthesis_VERSION_MAJOR 1)
set(relp_synthesis_VERSION_MINOR 0)
