######################################################################################
##                                                                                  ##
## CMake configuration for named plug-in.                                           ##
## This file is auto generated from plugins/config/pluginConf.cmake.in              ##
##                                                                                  ##
## Do not edit this file.                                                           ##
##                                                                                  ##
######################################################################################


# syllabification include directories
set(syllabification_include_path "/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/linguistic/syllabification/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/linguistic/syllabification/src")


# When included in other plug-in CMakeLists.txt, the above
# header directories will be appended to the plug-ins dirs.
list(APPEND ${plugin_lowercase_name}_INCLUDE_DIRS
  ${syllabification_include_path}
  )


# syllabification version
set(syllabification_VERSION_MAJOR 1)
set(syllabification_VERSION_MINOR 0)
