######################################################################################
##                                                                                  ##
## CMake configuration for named plug-in.                                           ##
## This file is auto generated from plugins/config/pluginConf.cmake.in              ##
##                                                                                  ##
## Do not edit this file.                                                           ##
##                                                                                  ##
######################################################################################


# track_float include directories
set(track_float_include_path "/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/utils/tracks/float/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/utils/tracks/float/src;/home/marco/Scrivania/SpeectInstaller/sources/speect/plugins/utils/matrices/float/src;/home/marco/Scrivania/SpeectInstaller/sources/Test/speect/plugins/utils/matrices/float/src")


# When included in other plug-in CMakeLists.txt, the above
# header directories will be appended to the plug-ins dirs.
list(APPEND ${plugin_lowercase_name}_INCLUDE_DIRS
  ${track_float_include_path}
  )


# track_float version
set(track_float_VERSION_MAJOR 1)
set(track_float_VERSION_MINOR 0)
